version: '3.1'

services:
    mongo:
        image: mongo
        container_name: mongo-recorder
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:27017
    minio:
        image: minio/minio
        container_name: minio
        ports:
            - '9000:9000'
            - '9001:9001' # MinIO web UI
        environment:
            MINIO_ROOT_USER: admin
            MINIO_ROOT_PASSWORD: password123
        volumes:
            - minio_data:/data
        command: ['server', '/data', '--console-address', ':9001']

volumes:
    minio_data:
