name: Deploy to GKE

on:
 push:
  branches:
   - main

env:
 PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
 GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
 GKE_ZONE: ${{ secrets.GKE_ZONE }}
 GAR_LOCATION: us-central1
 DEPLOYMENT_NAME: prod

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Set up Google Cloud
     uses: google-github-actions/auth@v1
     with:
      credentials_json: ${{ secrets.GCP_SA_KEY }}

   - name: Set up Docker auth
     run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

   - name: Set up kubectl
     uses: google-github-actions/get-gke-credentials@v1
     with:
      cluster_name: ${{ env.GKE_CLUSTER }}
      location: ${{ env.GKE_ZONE }}
      project_id: ${{ env.PROJECT_ID }}

   - name: Set up Kustomize
     run: |
      curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      sudo mv kustomize /usr/local/bin/

   - name: Build and Push Frontend
     run: |
      docker build -t gcr.io/${{ env.PROJECT_ID }}/frontend:${{ github.sha }} ./apps/frontend
      docker push gcr.io/${{ env.PROJECT_ID }}/frontend:${{ github.sha }}

   - name: Build and Push Backend
     run: |
      docker build -t gcr.io/${{ env.PROJECT_ID }}/backend:${{ github.sha }} ./apps/backend
      docker push gcr.io/${{ env.PROJECT_ID }}/backend:${{ github.sha }}

   - name: Update Kustomize Image Tags
     run: |
      kustomize edit set image frontend=gcr.io/${{ env.PROJECT_ID }}/frontend:${{ github.sha }}
      kustomize edit set image backend=gcr.io/${{ env.PROJECT_ID }}/backend:${{ github.sha }}
     working-directory: k8s/overlays/prod

   - name: Deploy to GKE
     run: |
      kubectl apply -k k8s/overlays/prod
